### ISSUE TITLE
Support for PostgreSQL 13

### ISSUE THREAD

**Issue by NunoFilipeSantos** [timescale/timescaledb#2779]
### What

This is a stop-gap release (outside our regular schedule) that aims to deliver PG13 support. 

---

### Why

Support for PostgreSQL 13 is a frequently requested feature from the community and PostgreSQL 13 was released September 24, 2020. 
PostgreSQL 13 offers significant improvements in performance and usability and in order to better support our users, we should include support for PG13 in this release.

---

### How

- [x] We need to adapt our code (code changes) to PG13.
- [x] Listing the new PG13 features that we need to add tests for https://github.com/timescale/timescaledb-private/issues/867 @mkindahl to complete
- [x] Testing new features in PG13 https://github.com/timescale/timescaledb-private/issues/868 @svenklemm to complete
- [x] Update CI build scripts https://github.com/timescale/timescaledb-private/issues/861
- [ ] Update packaging script to deliver TSDB with PG13 https://github.com/timescale/timescaledb-private/issues/864
- [ ] Update docker script to deliver TSDB with PG13 https://github.com/timescale/timescaledb-private/issues/863
- [ ]  Documentation needs to be updated to mention PG13, but no extensive documentation changes are expected. https://github.com/timescale/timescaledb-private/issues/865
- [ ] Update test for PG13, to be serialized after release of 2.1.

---

### Related PRs

https://github.com/timescale/timescaledb/pulls?q=is%3Apr+is%3Aopen+label%3APG13+

---
Reference: https://github.com/timescale/timescaledb-private/issues/593

**Comment by NunoFilipeSantos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support PostgreSQL 13](https://trello.com/c/MJRu6EDB/9-support-postgresql-13)

**Comment by sztanpet** [comment]
looks like this did not land with 2.0.1?
getting this error:

    -- Compiling against PostgreSQL version 13.1
    CMake Error at CMakeLists.txt:244 (message):
      TimescaleDB only supports PostgreSQL 11 and 12

**Comment by luss** [comment]
It is unclear to me whether the TimescaleDb folks are saying that the 2.0.x series is going to support PG13 in the near future.  I hope so, but...

**Comment by sztanpet** [comment]
well not really unclear, they definitely intend to, see https://docs.timescale.com/latest/release-notes

> What to expect from our next release
> For our next release (2.0.1), we plan to add:
> 
> Support for PostgreSQL 13: PG13 offers various improvements in performance and usability. We want to provide our users the latest and greatest versions of PG.

looked like the pg13 issues were solved though, but evidently not

**Comment by NunoFilipeSantos** [comment]
Hi! Yes, PG13 is planned for 2.1 it should be release during February 2021.

**Comment by NunoFilipeSantos** [comment]
PG 13 Expected release date: week of FEB 22.

**Comment by ignacioruiz** [comment]
Hi!

Wondering if it'll support all 13.X versions, including 13.2. Cheers!

**Comment by NunoFilipeSantos** [comment]
@ignacioruiz 13.2 comes with an important security fix.
