### ISSUE TITLE
[Enhancement]: Adopt multi-insert support for COPY

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#4080]
### Estimate

O: 1W
P: 3W

### What type of enhancement is this?

Performance

### What subsystems and features will be improved?

Data ingestion

### What does the enhancement do?

Recent PostgreSQL versions have enhancements inserting into partitioned tables. Essentially, the COPY path maintains multiple insert buffers, which can each correspond to a partition. Adopting this approach for chunk inserts should give better insert performance.

### Tasks
- [x] Backport PG 14 code into TS copy implementation
- [x] Handle `timescaledb.max_open_chunks_per_insert` chunk closes properly
- [x] Handle triggers on destination table properly (e.g., disable optimization and ignore `ts_insert_blocker` trigger).
- [x] Create testcases
- [x] Test multi-node integration
- [x] Check if any docs needs changing
- [x] Perform a rough benchmark test
- [ ] Final Demo

### Environment
PostgreSQL 13.6
Timescaledb 2.7.0-dev

Disk: Samsung SSD 850
Memory: 16 GB
CPU: Intel(R) Pentium(R) Silver J5005 CPU @ 1.50GHz

```c
#define MAX_BUFFERED_TUPLES 1000
#define MAX_BUFFERED_BYTES 65535
#define MAX_PARTITION_BUFFERS 32
```

### Benchmark Execution
```sql
---
-- Generate benchmark data
---

CREATE TABLE sensor_data(
time timestamp NOT NULL,
sensor_id integer NOT NULL,
cpu double precision,
temperature double precision);

INSERT INTO sensor_data
SELECT time + (INTERVAL '1 minute' * random()) AS time,
sensor_id, 
random() AS cpu, 
random()* 100 AS temperature
FROM
generate_series(now() - INTERVAL '1 months', now() - INTERVAL '1 day', INTERVAL '1 minutes') AS g1(time),
generate_series(1, 100, 1 ) AS g2(sensor_id)
ORDER BY time;

SELECT count(*) FROM sensor_data;
-- 4176100 elements

-- Export data
COPY sensor_data TO '/tmp/sensor_data.csv' DELIMITER ',' CSV HEADER;
DROP TABLE sensor_data;

---
-- Import data
---
CREATE TABLE sensor_data(
time timestamp NOT NULL,
sensor_id integer NOT NULL,
cpu double precision,
temperature double precision);

SELECT FROM create_hypertable(relation=>'sensor_data', time_column_name=> 'time', chunk_time_interval=>INTERVAL '24 hours');

-- Dry run to create hypertables
\timing
\copy sensor_data FROM /tmp/sensor_data.csv WITH csv header;

-- 30 Chunks are created
-- SELECT COUNT(*) FROM timescaledb_information.chunks WHERE hypertable_name='sensor_data';
-- Count: 30

TRUNCATE sensor_data;

-- Real import
SET client_min_messages TO DEBUG1;
\copy sensor_data FROM /tmp/sensor_data.csv WITH csv header;
```

### Result
```
Result (CIM_SINGLE)
COPY 4176100
Time: 98129.235 ms (01:38.129)

Result (CIM_MULTI)
COPY 4176100
Time: 83090.112 ms (01:23.090)

CIM_MULTI leads to approx 15% better performance
```
